FIPS_10_country_codes = [
 {'country_name': 'Afghanistan',
  'FIPS_10_country_code': 'AF',
  'noaa_country_code': 'AF',
  'fao_country_name': 'Afghanistan'},
 {'country_name': 'Albania',
  'FIPS_10_country_code': 'AL',
  'noaa_country_code': 'AL',
  'fao_country_name': 'Albania'},
 {'country_name': 'Algeria',
  'FIPS_10_country_code': 'AG',
  'noaa_country_code': 'AG',
  'fao_country_name': 'Algeria'},
 {'country_name': 'American Samoa',
  'FIPS_10_country_code': 'AQ',
  'noaa_country_code': 'AQ',
  'fao_country_name': 'American Samoa'},
 {'country_name': 'Andorra',
  'FIPS_10_country_code': 'AN',
  'noaa_country_code': 'AN',
  'fao_country_name': 'Andorra'},
 {'country_name': 'Angola',
  'FIPS_10_country_code': 'AO',
  'noaa_country_code': 'AO',
  'fao_country_name': 'Angola'},
 {'country_name': 'Anguilla',
  'FIPS_10_country_code': 'AV',
  'noaa_country_code': 'AV',
  'fao_country_name': 'Anguilla'},
 {'country_name': 'Antarctica',
  'FIPS_10_country_code': 'AY',
  'noaa_country_code': 'AY',
  'fao_country_name': 'Antarctica'},
 {'country_name': 'Antigua and Barbuda',
  'FIPS_10_country_code': 'AC',
  'noaa_country_code': 'AC',
  'fao_country_name': 'Antigua and Barbuda'},
 {'country_name': 'Argentina',
  'FIPS_10_country_code': 'AR',
  'noaa_country_code': 'AR',
  'fao_country_name': 'Argentina'},
 {'country_name': 'Armenia',
  'FIPS_10_country_code': 'AM',
  'noaa_country_code': 'AM',
  'fao_country_name': 'Armenia'},
 {'country_name': 'Aruba',
  'FIPS_10_country_code': 'AA',
  'noaa_country_code': 'AA',
  'fao_country_name': 'Aruba'},
 {'country_name': 'Australia',
  'FIPS_10_country_code': 'AS',
  'noaa_country_code': 'AS',
  'fao_country_name': 'Australia'},
 {'country_name': 'Austria',
  'FIPS_10_country_code': 'AU',
  'noaa_country_code': 'AU',
  'fao_country_name': 'Austria'},
 {'country_name': 'Azerbaijan',
  'FIPS_10_country_code': 'AJ',
  'noaa_country_code': 'AJ',
  'fao_country_name': 'Azerbaijan'},
 {'country_name': 'Bahamas',
  'FIPS_10_country_code': 'BF',
  'noaa_country_code': 'BF',
  'fao_country_name': 'Bahamas'},
 {'country_name': 'Bahrain',
  'FIPS_10_country_code': 'BA',
  'noaa_country_code': 'BA',
  'fao_country_name': 'Bahrain'},
 {'country_name': 'Bangladesh',
  'FIPS_10_country_code': 'BG',
  'noaa_country_code': 'BG',
  'fao_country_name': 'Bangladesh'},
 {'country_name': 'Barbados',
  'FIPS_10_country_code': 'BB',
  'noaa_country_code': 'BB',
  'fao_country_name': 'Barbados'},
 {'country_name': 'Belarus',
  'FIPS_10_country_code': 'BO',
  'noaa_country_code': 'BO',
  'fao_country_name': 'Belarus'},
 {'country_name': 'Belgium',
  'FIPS_10_country_code': 'BE',
  'noaa_country_code': 'BE',
  'fao_country_name': 'Belgium'},
 {'country_name': 'Belize',
  'FIPS_10_country_code': 'BH',
  'noaa_country_code': 'BH',
  'fao_country_name': 'Belize'},
 {'country_name': 'Benin',
  'FIPS_10_country_code': 'BN',
  'noaa_country_code': 'BN',
  'fao_country_name': 'Benin'},
 {'country_name': 'Bermuda',
  'FIPS_10_country_code': 'BD',
  'noaa_country_code': 'BD',
  'fao_country_name': 'Bermuda'},
 {'country_name': 'Bhutan',
  'FIPS_10_country_code': 'BT',
  'noaa_country_code': 'BT',
  'fao_country_name': 'Bhutan'},
 {'country_name': 'Bolivia (Plurinational State of)',
  'FIPS_10_country_code': 'BL',
  'noaa_country_code': 'BL',
  'fao_country_name': 'Bolivia (Plurinational State of)'},
 {'country_name': 'Bosnia and Herzegovina',
  'FIPS_10_country_code': 'BK',
  'noaa_country_code': 'BK',
  'fao_country_name': 'Bosnia and Herzegovina'},
 {'country_name': 'Botswana',
  'FIPS_10_country_code': 'BC',
  'noaa_country_code': 'BC',
  'fao_country_name': 'Botswana'},
 {'country_name': 'Bouvet Island',
  'FIPS_10_country_code': 'BV',
  'noaa_country_code': 'BV',
  'fao_country_name': 'Bouvet Island'},
 {'country_name': 'Brazil',
  'FIPS_10_country_code': 'BR',
  'noaa_country_code': 'BR',
  'fao_country_name': 'Brazil'},
 {'country_name': 'British Indian Ocean Territory',
  'FIPS_10_country_code': 'IO',
  'noaa_country_code': 'IO',
  'fao_country_name': 'British Indian Ocean Territory'},
 {'country_name': 'Brunei Darussalam',
  'FIPS_10_country_code': 'BX',
  'noaa_country_code': 'BX',
  'fao_country_name': 'Brunei Darussalam'},
 {'country_name': 'Bulgaria',
  'FIPS_10_country_code': 'BU',
  'noaa_country_code': 'BU',
  'fao_country_name': 'Bulgaria'},
 {'country_name': 'Burkina Faso',
  'FIPS_10_country_code': 'UV',
  'noaa_country_code': 'UV',
  'fao_country_name': 'Burkina Faso'},
 {'country_name': 'Burundi',
  'FIPS_10_country_code': 'BY',
  'noaa_country_code': 'BY',
  'fao_country_name': 'Burundi'},
 {'country_name': 'Cabo Verde',
  'FIPS_10_country_code': 'CV',
  'noaa_country_code': 'CV',
  'fao_country_name': 'Cabo Verde'},
 {'country_name': 'Cambodia',
  'FIPS_10_country_code': 'CB',
  'noaa_country_code': 'CB',
  'fao_country_name': 'Cambodia'},
 {'country_name': 'Cameroon',
  'FIPS_10_country_code': 'CM',
  'noaa_country_code': 'CM',
  'fao_country_name': 'Cameroon'},
 {'country_name': 'Canada',
  'FIPS_10_country_code': 'CA',
  'noaa_country_code': 'CA',
  'fao_country_name': 'Canada'},
 {'country_name': 'Cayman Islands',
  'FIPS_10_country_code': 'CJ',
  'noaa_country_code': 'CJ',
  'fao_country_name': 'Cayman Islands'},
 {'country_name': 'Central African Republic',
  'FIPS_10_country_code': 'CT',
  'noaa_country_code': 'CT',
  'fao_country_name': 'Central African Republic'},
 {'country_name': 'Chad',
  'FIPS_10_country_code': 'CD',
  'noaa_country_code': 'CD',
  'fao_country_name': 'Chad'},
 {'country_name': 'Chile',
  'FIPS_10_country_code': 'CI',
  'noaa_country_code': 'CI',
  'fao_country_name': 'Chile'},
 {'country_name': 'China',
  'FIPS_10_country_code': 'CH',
  'noaa_country_code': 'CH',
  'fao_country_name': 'China, mainland'},
 {'country_name': 'Christmas Island',
  'FIPS_10_country_code': 'KT',
  'noaa_country_code': 'KT',
  'fao_country_name': 'Christmas Island'},
 {'country_name': 'Cocos (Keeling) Islands',
  'FIPS_10_country_code': 'CK',
  'noaa_country_code': 'CK',
  'fao_country_name': 'Cocos (Keeling) Islands'},
 {'country_name': 'Colombia',
  'FIPS_10_country_code': 'CO',
  'noaa_country_code': 'CO',
  'fao_country_name': 'Colombia'},
 {'country_name': 'Comoros',
  'FIPS_10_country_code': 'CN',
  'noaa_country_code': 'CN',
  'fao_country_name': 'Comoros'},
 {'country_name': 'Congo',
  'FIPS_10_country_code': 'CF',
  'noaa_country_code': 'CF',
  'fao_country_name': 'Congo'},
 {'country_name': 'Congo (Democratic Republic of the)',
  'FIPS_10_country_code': 'CG',
  'noaa_country_code': 'CG',
  'fao_country_name': 'Democratic Republic of the Congo'},
 {'country_name': 'Cook Islands',
  'FIPS_10_country_code': 'CW',
  'noaa_country_code': 'CW',
  'fao_country_name': 'Cook Islands'},
 {'country_name': 'Costa Rica',
  'FIPS_10_country_code': 'CS',
  'noaa_country_code': 'CS',
  'fao_country_name': 'Costa Rica'},
 {'country_name': "Cote d'Ivoire",
  'FIPS_10_country_code': 'IV',
  'noaa_country_code': 'IV',
  'fao_country_name': "Côte d'Ivoire"},
 {'country_name': 'Croatia',
  'FIPS_10_country_code': 'HR',
  'noaa_country_code': 'HR',
  'fao_country_name': 'Croatia'},
 {'country_name': 'Cuba',
  'FIPS_10_country_code': 'CU',
  'noaa_country_code': 'CU',
  'fao_country_name': 'Cuba'},
 {'country_name': 'Curacao',
  'FIPS_10_country_code': 'UC',
  'noaa_country_code': 'UC',
  'fao_country_name': 'Curacao'},
 {'country_name': 'Cyprus',
  'FIPS_10_country_code': 'CY',
  'noaa_country_code': 'CY',
  'fao_country_name': 'Cyprus'},
 {'country_name': 'Czechia',
  'FIPS_10_country_code': 'EZ',
  'noaa_country_code': 'EZ',
  'fao_country_name': 'Czechia'},
 {'country_name': 'Denmark',
  'FIPS_10_country_code': 'DK',
  'noaa_country_code': 'DA',
  'fao_country_name': 'Denmark'},
 {'country_name': 'Djibouti',
  'FIPS_10_country_code': 'DJ',
  'noaa_country_code': 'DJ',
  'fao_country_name': 'Djibouti'},
 {'country_name': 'Dominica',
  'FIPS_10_country_code': 'DO',
  'noaa_country_code': 'DO',
  'fao_country_name': 'Dominica'},
 {'country_name': 'Dominican Republic',
  'FIPS_10_country_code': 'DR',
  'noaa_country_code': 'DR',
  'fao_country_name': 'Dominican Republic'},
 {'country_name': 'Ecuador',
  'FIPS_10_country_code': 'EC',
  'noaa_country_code': 'EC',
  'fao_country_name': 'Ecuador'},
 {'country_name': 'Egypt',
  'FIPS_10_country_code': 'EG',
  'noaa_country_code': 'EG',
  'fao_country_name': 'Egypt'},
 {'country_name': 'El Salvador',
  'FIPS_10_country_code': 'ES',
  'noaa_country_code': 'ES',
  'fao_country_name': 'El Salvador'},
 {'country_name': 'Equatorial Guinea',
  'FIPS_10_country_code': 'EK',
  'noaa_country_code': 'EK',
  'fao_country_name': 'Equatorial Guinea'},
 {'country_name': 'Eritrea',
  'FIPS_10_country_code': 'ER',
  'noaa_country_code': 'ER',
  'fao_country_name': 'Eritrea'},
 {'country_name': 'Estonia',
  'FIPS_10_country_code': 'EN',
  'noaa_country_code': 'EN',
  'fao_country_name': 'Estonia'},
 {'country_name': 'Ethiopia',
  'FIPS_10_country_code': 'ET',
  'noaa_country_code': 'ET',
  'fao_country_name': 'Ethiopia'},
 {'country_name': 'Falkland Islands (Malvinas)',
  'FIPS_10_country_code': 'FK',
  'noaa_country_code': 'FK',
  'fao_country_name': 'Falkland Islands (Malvinas)'},
 {'country_name': 'Faroe Islands',
  'FIPS_10_country_code': 'FO',
  'noaa_country_code': 'FO',
  'fao_country_name': 'Faroe Islands'},
 {'country_name': 'Fiji',
  'FIPS_10_country_code': 'FJ',
  'noaa_country_code': 'FJ',
  'fao_country_name': 'Fiji'},
 {'country_name': 'Finland',
  'FIPS_10_country_code': 'FI',
  'noaa_country_code': 'FI',
  'fao_country_name': 'Finland'},
 {'country_name': 'France',
  'FIPS_10_country_code': 'FR',
  'noaa_country_code': 'FR',
  'fao_country_name': 'France'},
 {'country_name': 'French Guiana',
  'FIPS_10_country_code': 'FG',
  'noaa_country_code': 'FG',
  'fao_country_name': 'French Guiana'},
 {'country_name': 'French Polynesia',
  'FIPS_10_country_code': 'FP',
  'noaa_country_code': 'FP',
  'fao_country_name': 'French Polynesia'},
 {'country_name': 'French Southern Territories',
  'FIPS_10_country_code': 'FS',
  'noaa_country_code': 'FS',
  'fao_country_name': 'French Southern Territories'},
 {'country_name': 'Gabon',
  'FIPS_10_country_code': 'GB',
  'noaa_country_code': 'GB',
  'fao_country_name': 'Gabon'},
 {'country_name': 'Gambia',
  'FIPS_10_country_code': 'GA',
  'noaa_country_code': 'GA',
  'fao_country_name': 'Gambia'},
 {'country_name': 'Georgia',
  'FIPS_10_country_code': 'GG',
  'noaa_country_code': 'GG',
  'fao_country_name': 'Georgia'},
 {'country_name': 'Germany',
  'FIPS_10_country_code': 'GM',
  'noaa_country_code': 'GM',
  'fao_country_name': 'Germany'},
 {'country_name': 'Ghana',
  'FIPS_10_country_code': 'GH',
  'noaa_country_code': 'GH',
  'fao_country_name': 'Ghana'},
 {'country_name': 'Gibraltar',
  'FIPS_10_country_code': 'GI',
  'noaa_country_code': 'GI',
  'fao_country_name': 'Gibraltar'},
 {'country_name': 'Greece',
  'FIPS_10_country_code': 'GR',
  'noaa_country_code': 'GR',
  'fao_country_name': 'Greece'},
 {'country_name': 'Greenland',
  'FIPS_10_country_code': 'GL',
  'noaa_country_code': 'GL',
  'fao_country_name': 'Greenland'},
 {'country_name': 'Grenada',
  'FIPS_10_country_code': 'GJ',
  'noaa_country_code': 'GJ',
  'fao_country_name': 'Grenada'},
 {'country_name': 'Guadeloupe',
  'FIPS_10_country_code': 'GP',
  'noaa_country_code': 'GP',
  'fao_country_name': 'Guadeloupe'},
 {'country_name': 'Guam',
  'FIPS_10_country_code': 'GQ',
  'noaa_country_code': 'GQ',
  'fao_country_name': 'Guam'},
 {'country_name': 'Guatemala',
  'FIPS_10_country_code': 'GT',
  'noaa_country_code': 'GT',
  'fao_country_name': 'Guatemala'},
 {'country_name': 'Guernsey',
  'FIPS_10_country_code': 'GK',
  'noaa_country_code': 'GK',
  'fao_country_name': 'Guernsey'},
 {'country_name': 'Guinea',
  'FIPS_10_country_code': 'GV',
  'noaa_country_code': 'GV',
  'fao_country_name': 'Guinea'},
 {'country_name': 'Guinea-Bissau',
  'FIPS_10_country_code': 'PU',
  'noaa_country_code': 'PU',
  'fao_country_name': 'Guinea-Bissau'},
 {'country_name': 'Guyana',
  'FIPS_10_country_code': 'GY',
  'noaa_country_code': 'GY',
  'fao_country_name': 'Guyana'},
 {'country_name': 'Haiti',
  'FIPS_10_country_code': 'HA',
  'noaa_country_code': 'HA',
  'fao_country_name': 'Haiti'},
 {'country_name': 'Heard Island and McDonald Islands',
  'FIPS_10_country_code': 'HM',
  'noaa_country_code': 'HM',
  'fao_country_name': 'Heard Island and McDonald Islands'},
 {'country_name': 'Holy See',
  'FIPS_10_country_code': 'VT',
  'noaa_country_code': 'VT',
  'fao_country_name': 'Holy See'},
 {'country_name': 'Honduras',
  'FIPS_10_country_code': 'HO',
  'noaa_country_code': 'HO',
  'fao_country_name': 'Honduras'},
 {'country_name': 'Hong Kong',
  'FIPS_10_country_code': 'HK',
  'noaa_country_code': 'HK',
  'fao_country_name': 'China, Hong Kong SAR'},
 {'country_name': 'Hungary',
  'FIPS_10_country_code': 'HU',
  'noaa_country_code': 'HU',
  'fao_country_name': 'Hungary'},
 {'country_name': 'Iceland',
  'FIPS_10_country_code': 'IC',
  'noaa_country_code': 'IC',
  'fao_country_name': 'Iceland'},
 {'country_name': 'India',
  'FIPS_10_country_code': 'IN',
  'noaa_country_code': 'IN',
  'fao_country_name': 'India'},
 {'country_name': 'Indonesia',
  'FIPS_10_country_code': 'ID',
  'noaa_country_code': 'ID',
  'fao_country_name': 'Indonesia'},
 {'country_name': 'Iran (Islamic Republic of)',
  'FIPS_10_country_code': 'IR',
  'noaa_country_code': 'IR',
  'fao_country_name': 'Iran (Islamic Republic of)'},
 {'country_name': 'Iraq',
  'FIPS_10_country_code': 'IZ',
  'noaa_country_code': 'IZ',
  'fao_country_name': 'Iraq'},
 {'country_name': 'Ireland',
  'FIPS_10_country_code': 'EI',
  'noaa_country_code': 'EI',
  'fao_country_name': 'Ireland'},
 {'country_name': 'Isle of Man',
  'FIPS_10_country_code': 'IM',
  'noaa_country_code': 'IM',
  'fao_country_name': 'Isle of Man'},
 {'country_name': 'Israel',
  'FIPS_10_country_code': 'IS',
  'noaa_country_code': 'IS',
  'fao_country_name': 'Israel'},
 {'country_name': 'Italy',
  'FIPS_10_country_code': 'IT',
  'noaa_country_code': 'IT',
  'fao_country_name': 'Italy'},
 {'country_name': 'Jamaica',
  'FIPS_10_country_code': 'JM',
  'noaa_country_code': 'JM',
  'fao_country_name': 'Jamaica'},
 {'country_name': 'Japan',
  'FIPS_10_country_code': 'JA',
  'noaa_country_code': 'JA',
  'fao_country_name': 'Japan'},
 {'country_name': 'Jersey',
  'FIPS_10_country_code': 'JE',
  'noaa_country_code': 'JE',
  'fao_country_name': 'Jersey'},
 {'country_name': 'Jordan',
  'FIPS_10_country_code': 'JO',
  'noaa_country_code': 'JO',
  'fao_country_name': 'Jordan'},
 {'country_name': 'Kazakhstan',
  'FIPS_10_country_code': 'KZ',
  'noaa_country_code': 'KZ',
  'fao_country_name': 'Kazakhstan'},
 {'country_name': 'Kenya',
  'FIPS_10_country_code': 'KE',
  'noaa_country_code': 'KE',
  'fao_country_name': 'Kenya'},
 {'country_name': 'Kiribati',
  'FIPS_10_country_code': 'KR',
  'noaa_country_code': 'KR',
  'fao_country_name': 'Kiribati'},
 {'country_name': "Korea (Democratic People's Republic of)",
  'FIPS_10_country_code': 'KN',
  'noaa_country_code': 'KN',
  'fao_country_name': "Democratic People's Republic of Korea"},
 {'country_name': 'Korea (Republic of)',
  'FIPS_10_country_code': 'KS',
  'noaa_country_code': 'KS',
  'fao_country_name': 'Republic of Korea'},
 {'country_name': 'Kuwait',
  'FIPS_10_country_code': 'KU',
  'noaa_country_code': 'KU',
  'fao_country_name': 'Kuwait'},
 {'country_name': 'Kyrgyzstan',
  'FIPS_10_country_code': 'KG',
  'noaa_country_code': 'KG',
  'fao_country_name': 'Kyrgyzstan'},
 {'country_name': "Lao People's Democratic Republic",
  'FIPS_10_country_code': 'LA',
  'noaa_country_code': 'LA',
  'fao_country_name': "Lao People's Democratic Republic"},
 {'country_name': 'Latvia',
  'FIPS_10_country_code': 'LG',
  'noaa_country_code': 'LG',
  'fao_country_name': 'Latvia'},
 {'country_name': 'Lebanon',
  'FIPS_10_country_code': 'LE',
  'noaa_country_code': 'LE',
  'fao_country_name': 'Lebanon'},
 {'country_name': 'Lesotho',
  'FIPS_10_country_code': 'LT',
  'noaa_country_code': 'LT',
  'fao_country_name': 'Lesotho'},
 {'country_name': 'Liberia',
  'FIPS_10_country_code': 'LI',
  'noaa_country_code': 'LI',
  'fao_country_name': 'Liberia'},
 {'country_name': 'Libya',
  'FIPS_10_country_code': 'LY',
  'noaa_country_code': 'LY',
  'fao_country_name': 'Libya'},
 {'country_name': 'Liechtenstein',
  'FIPS_10_country_code': 'LS',
  'noaa_country_code': 'LS',
  'fao_country_name': 'Liechtenstein'},
 {'country_name': 'Lithuania',
  'FIPS_10_country_code': 'LH',
  'noaa_country_code': 'LH',
  'fao_country_name': 'Lithuania'},
 {'country_name': 'Luxembourg',
  'FIPS_10_country_code': 'LU',
  'noaa_country_code': 'LU',
  'fao_country_name': 'Luxembourg'},
 {'country_name': 'Macao',
  'FIPS_10_country_code': 'MC',
  'noaa_country_code': 'MC',
  'fao_country_name': 'China, Macao SAR'},
 {'country_name': 'North Macedonia',
  'FIPS_10_country_code': 'MK',
  'noaa_country_code': 'MK',
  'fao_country_name': 'North Macedonia'},
 {'country_name': 'Madagascar',
  'FIPS_10_country_code': 'MA',
  'noaa_country_code': 'MA',
  'fao_country_name': 'Madagascar'},
 {'country_name': 'Malawi',
  'FIPS_10_country_code': 'MI',
  'noaa_country_code': 'MI',
  'fao_country_name': 'Malawi'},
 {'country_name': 'Malaysia',
  'FIPS_10_country_code': 'MY',
  'noaa_country_code': 'MY',
  'fao_country_name': 'Malaysia'},
 {'country_name': 'Maldives',
  'FIPS_10_country_code': 'MV',
  'noaa_country_code': 'MV',
  'fao_country_name': 'Maldives'},
 {'country_name': 'Mali',
  'FIPS_10_country_code': 'ML',
  'noaa_country_code': 'ML',
  'fao_country_name': 'Mali'},
 {'country_name': 'Malta',
  'FIPS_10_country_code': 'MT',
  'noaa_country_code': 'MT',
  'fao_country_name': 'Malta'},
 {'country_name': 'Marshall Islands',
  'FIPS_10_country_code': 'RM',
  'noaa_country_code': 'RM',
  'fao_country_name': 'Marshall Islands'},
 {'country_name': 'Martinique',
  'FIPS_10_country_code': 'MB',
  'noaa_country_code': 'MB',
  'fao_country_name': 'Martinique'},
 {'country_name': 'Mauritania',
  'FIPS_10_country_code': 'MR',
  'noaa_country_code': 'MR',
  'fao_country_name': 'Mauritania'},
 {'country_name': 'Mauritius',
  'FIPS_10_country_code': 'MP',
  'noaa_country_code': 'MP',
  'fao_country_name': 'Mauritius'},
 {'country_name': 'Mayotte',
  'FIPS_10_country_code': 'MF',
  'noaa_country_code': 'MF',
  'fao_country_name': 'Mayotte'},
 {'country_name': 'Mexico',
  'FIPS_10_country_code': 'MX',
  'noaa_country_code': 'MX',
  'fao_country_name': 'Mexico'},
 {'country_name': 'Micronesia (Federated States of)',
  'FIPS_10_country_code': 'FM',
  'noaa_country_code': 'FM',
  'fao_country_name': 'Micronesia (Federated States of)'},
 {'country_name': 'Moldova (Republic of)',
  'FIPS_10_country_code': 'MD',
  'noaa_country_code': 'MD',
  'fao_country_name': 'Republic of Moldova'},
 {'country_name': 'Monaco',
  'FIPS_10_country_code': 'MN',
  'noaa_country_code': 'MN',
  'fao_country_name': 'Monaco'},
 {'country_name': 'Mongolia',
  'FIPS_10_country_code': 'MG',
  'noaa_country_code': 'MG',
  'fao_country_name': 'Mongolia'},
 {'country_name': 'Montenegro',
  'FIPS_10_country_code': 'MJ',
  'noaa_country_code': 'MJ',
  'fao_country_name': 'Montenegro'},
 {'country_name': 'Montserrat',
  'FIPS_10_country_code': 'MH',
  'noaa_country_code': 'MH',
  'fao_country_name': 'Montserrat'},
 {'country_name': 'Morocco',
  'FIPS_10_country_code': 'MO',
  'noaa_country_code': 'MO',
  'fao_country_name': 'Morocco'},
 {'country_name': 'Mozambique',
  'FIPS_10_country_code': 'MZ',
  'noaa_country_code': 'MZ',
  'fao_country_name': 'Mozambique'},
 {'country_name': 'Myanmar',
  'FIPS_10_country_code': 'BM',
  'noaa_country_code': 'BM',
  'fao_country_name': 'Myanmar'},
 {'country_name': 'Namibia',
  'FIPS_10_country_code': 'WA',
  'noaa_country_code': 'WA',
  'fao_country_name': 'Namibia'},
 {'country_name': 'Nauru',
  'FIPS_10_country_code': 'NR',
  'noaa_country_code': 'NR',
  'fao_country_name': 'Nauru'},
 {'country_name': 'Nepal',
  'FIPS_10_country_code': 'NP',
  'noaa_country_code': 'NP',
  'fao_country_name': 'Nepal'},
 {'country_name': 'Netherlands',
  'FIPS_10_country_code': 'NL',
  'noaa_country_code': 'NL',
  'fao_country_name': 'Netherlands'},
 {'country_name': 'New Caledonia',
  'FIPS_10_country_code': 'NC',
  'noaa_country_code': 'NC',
  'fao_country_name': 'New Caledonia'},
 {'country_name': 'New Zealand',
  'FIPS_10_country_code': 'NZ',
  'noaa_country_code': 'NZ',
  'fao_country_name': 'New Zealand'},
 {'country_name': 'Nicaragua',
  'FIPS_10_country_code': 'NU',
  'noaa_country_code': 'NU',
  'fao_country_name': 'Nicaragua'},
 {'country_name': 'Niger',
  'FIPS_10_country_code': 'NG',
  'noaa_country_code': 'NG',
  'fao_country_name': 'Niger'},
 {'country_name': 'Nigeria',
  'FIPS_10_country_code': 'NI',
  'noaa_country_code': 'NI',
  'fao_country_name': 'Nigeria'},
 {'country_name': 'Niue',
  'FIPS_10_country_code': 'NE',
  'noaa_country_code': 'NE',
  'fao_country_name': 'Niue'},
 {'country_name': 'Norfolk Island',
  'FIPS_10_country_code': 'NF',
  'noaa_country_code': 'NF',
  'fao_country_name': 'Norfolk Island'},
 {'country_name': 'Northern Mariana Islands',
  'FIPS_10_country_code': 'CQ',
  'noaa_country_code': 'CQ',
  'fao_country_name': 'Northern Mariana Islands'},
 {'country_name': 'Norway',
  'FIPS_10_country_code': 'NO',
  'noaa_country_code': 'NO',
  'fao_country_name': 'Norway'},
 {'country_name': 'Oman',
  'FIPS_10_country_code': 'MU',
  'noaa_country_code': 'MU',
  'fao_country_name': 'Oman'},
 {'country_name': 'Pakistan',
  'FIPS_10_country_code': 'PK',
  'noaa_country_code': 'PK',
  'fao_country_name': 'Pakistan'},
 {'country_name': 'Palau',
  'FIPS_10_country_code': 'PS',
  'noaa_country_code': 'PS',
  'fao_country_name': 'Palau'},
 {'country_name': 'Palestine, State of',
  'FIPS_10_country_code': 'WE',
  'noaa_country_code': 'WE',
  'fao_country_name': 'Palestine'},
 {'country_name': 'Panama',
  'FIPS_10_country_code': 'PM',
  'noaa_country_code': 'PM',
  'fao_country_name': 'Panama'},
 {'country_name': 'Papua New Guinea',
  'FIPS_10_country_code': 'PP',
  'noaa_country_code': 'PP',
  'fao_country_name': 'Papua New Guinea'},
 {'country_name': 'Paraguay',
  'FIPS_10_country_code': 'PA',
  'noaa_country_code': 'PA',
  'fao_country_name': 'Paraguay'},
 {'country_name': 'Peru',
  'FIPS_10_country_code': 'PE',
  'noaa_country_code': 'PE',
  'fao_country_name': 'Peru'},
 {'country_name': 'Philippines',
  'FIPS_10_country_code': 'RP',
  'noaa_country_code': 'RP',
  'fao_country_name': 'Philippines'},
 {'country_name': 'Pitcairn',
  'FIPS_10_country_code': 'PC',
  'noaa_country_code': 'PC',
  'fao_country_name': 'Pitcairn'},
 {'country_name': 'Poland',
  'FIPS_10_country_code': 'PL',
  'noaa_country_code': 'PL',
  'fao_country_name': 'Poland'},
 {'country_name': 'Portugal',
  'FIPS_10_country_code': 'PO',
  'noaa_country_code': 'PO',
  'fao_country_name': 'Portugal'},
 {'country_name': 'Puerto Rico',
  'FIPS_10_country_code': 'RQ',
  'noaa_country_code': 'RQ',
  'fao_country_name': 'Puerto Rico'},
 {'country_name': 'Qatar',
  'FIPS_10_country_code': 'QA',
  'noaa_country_code': 'QA',
  'fao_country_name': 'Qatar'},
 {'country_name': 'Reunion',
  'FIPS_10_country_code': 'RE',
  'noaa_country_code': 'RE',
  'fao_country_name': 'Réunion'},
 {'country_name': 'Romania',
  'FIPS_10_country_code': 'RO',
  'noaa_country_code': 'RO',
  'fao_country_name': 'Romania'},
 {'country_name': 'Russian Federation',
  'FIPS_10_country_code': 'RS',
  'noaa_country_code': 'RS',
  'fao_country_name': 'Russian Federation'},
 {'country_name': 'Rwanda',
  'FIPS_10_country_code': 'RW',
  'noaa_country_code': 'RW',
  'fao_country_name': 'Rwanda'},
 {'country_name': 'Saint Barthelemy',
  'FIPS_10_country_code': 'TB',
  'noaa_country_code': 'TB',
  'fao_country_name': 'Saint Barthelemy'},
 {'country_name': 'Saint Helena, Ascension and Tristan da Cunha',
  'FIPS_10_country_code': 'SH',
  'noaa_country_code': 'SH',
  'fao_country_name': 'Saint Helena, Ascension and Tristan da Cunha'},
 {'country_name': 'Saint Kitts and Nevis',
  'FIPS_10_country_code': 'SC',
  'noaa_country_code': 'SC',
  'fao_country_name': 'Saint Kitts and Nevis'},
 {'country_name': 'Saint Lucia',
  'FIPS_10_country_code': 'ST',
  'noaa_country_code': 'ST',
  'fao_country_name': 'Saint Lucia'},
 {'country_name': 'Saint Martin',
  'FIPS_10_country_code': 'RN',
  'noaa_country_code': 'RN',
  'fao_country_name': 'Saint Martin'},
 {'country_name': 'Saint Pierre and Miquelon',
  'FIPS_10_country_code': 'SB',
  'noaa_country_code': 'SB',
  'fao_country_name': 'Saint Pierre and Miquelon'},
 {'country_name': 'Saint Vincent and the Grenadines',
  'FIPS_10_country_code': 'VC',
  'noaa_country_code': 'VC',
  'fao_country_name': 'Saint Vincent and the Grenadines'},
 {'country_name': 'Samoa',
  'FIPS_10_country_code': 'WS',
  'noaa_country_code': 'WS',
  'fao_country_name': 'Samoa'},
 {'country_name': 'San Marino',
  'FIPS_10_country_code': 'SM',
  'noaa_country_code': 'SM',
  'fao_country_name': 'San Marino'},
 {'country_name': 'Sao Tome and Principe',
  'FIPS_10_country_code': 'TP',
  'noaa_country_code': 'TP',
  'fao_country_name': 'Sao Tome and Principe'},
 {'country_name': 'Saudi Arabia',
  'FIPS_10_country_code': 'SA',
  'noaa_country_code': 'SA',
  'fao_country_name': 'Saudi Arabia'},
 {'country_name': 'Senegal',
  'FIPS_10_country_code': 'SG',
  'noaa_country_code': 'SG',
  'fao_country_name': 'Senegal'},
 {'country_name': 'Serbia',
  'FIPS_10_country_code': 'RI',
  'noaa_country_code': 'RI',
  'fao_country_name': 'Serbia'},
 {'country_name': 'Seychelles',
  'FIPS_10_country_code': 'SE',
  'noaa_country_code': 'SE',
  'fao_country_name': 'Seychelles'},
 {'country_name': 'Sierra Leone',
  'FIPS_10_country_code': 'SL',
  'noaa_country_code': 'SL',
  'fao_country_name': 'Sierra Leone'},
 {'country_name': 'Singapore',
  'FIPS_10_country_code': 'SN',
  'noaa_country_code': 'SN',
  'fao_country_name': 'Singapore'},
 {'country_name': 'Sint Maarten',
  'FIPS_10_country_code': 'NN',
  'noaa_country_code': 'NN',
  'fao_country_name': 'Sint Maarten'},
 {'country_name': 'Slovakia',
  'FIPS_10_country_code': 'LO',
  'noaa_country_code': 'LO',
  'fao_country_name': 'Slovakia'},
 {'country_name': 'Slovenia',
  'FIPS_10_country_code': 'SI',
  'noaa_country_code': 'SI',
  'fao_country_name': 'Slovenia'},
 {'country_name': 'Solomon Islands',
  'FIPS_10_country_code': 'BP',
  'noaa_country_code': 'BP',
  'fao_country_name': 'Solomon Islands'},
 {'country_name': 'Somalia',
  'FIPS_10_country_code': 'SO',
  'noaa_country_code': 'SO',
  'fao_country_name': 'Somalia'},
 {'country_name': 'South Africa',
  'FIPS_10_country_code': 'SF',
  'noaa_country_code': 'SF',
  'fao_country_name': 'South Africa'},
 {'country_name': 'South Georgia and the South Sandwich Islands',
  'FIPS_10_country_code': 'SX',
  'noaa_country_code': 'SX',
  'fao_country_name': 'South Georgia and the South Sandwich Islands'},
 {'country_name': 'South Sudan',
  'FIPS_10_country_code': 'OD',
  'noaa_country_code': 'OD',
  'fao_country_name': 'South Sudan'},
 {'country_name': 'Spain',
  'FIPS_10_country_code': 'SP',
  'noaa_country_code': 'SP',
  'fao_country_name': 'Spain'},
 {'country_name': 'Sri Lanka',
  'FIPS_10_country_code': 'CE',
  'noaa_country_code': 'CE',
  'fao_country_name': 'Sri Lanka'},
 {'country_name': 'Sudan',
  'FIPS_10_country_code': 'SU',
  'noaa_country_code': 'SU',
  'fao_country_name': 'Sudan'},
 {'country_name': 'Suriname',
  'FIPS_10_country_code': 'NS',
  'noaa_country_code': 'NS',
  'fao_country_name': 'Suriname'},
 {'country_name': 'Svalbard and Jan Mayen',
  'FIPS_10_country_code': 'SV',
  'noaa_country_code': 'SV',
  'fao_country_name': 'Svalbard and Jan Mayen'},
 {'country_name': 'Eswatini',
  'FIPS_10_country_code': 'WZ',
  'noaa_country_code': 'WZ',
  'fao_country_name': 'Eswatini'},
 {'country_name': 'Sweden',
  'FIPS_10_country_code': 'SW',
  'noaa_country_code': 'SW',
  'fao_country_name': 'Sweden'},
 {'country_name': 'Switzerland',
  'FIPS_10_country_code': 'SZ',
  'noaa_country_code': 'SZ',
  'fao_country_name': 'Switzerland'},
 {'country_name': 'Syrian Arab Republic',
  'FIPS_10_country_code': 'SY',
  'noaa_country_code': 'SY',
  'fao_country_name': 'Syrian Arab Republic'},
 {'country_name': 'Taiwan (Province of China)',
  'FIPS_10_country_code': 'TW',
  'noaa_country_code': 'TW',
  'fao_country_name': 'China, Taiwan Province of'},
 {'country_name': 'Tajikistan',
  'FIPS_10_country_code': 'TI',
  'noaa_country_code': 'TI',
  'fao_country_name': 'Tajikistan'},
 {'country_name': 'Tanzania, United Republic of',
  'FIPS_10_country_code': 'TZ',
  'noaa_country_code': 'TZ',
  'fao_country_name': 'United Republic of Tanzania'},
 {'country_name': 'Thailand',
  'FIPS_10_country_code': 'TH',
  'noaa_country_code': 'TH',
  'fao_country_name': 'Thailand'},
 {'country_name': 'Timor-Leste',
  'FIPS_10_country_code': 'TT',
  'noaa_country_code': 'TT',
  'fao_country_name': 'Timor-Leste'},
 {'country_name': 'Togo',
  'FIPS_10_country_code': 'TO',
  'noaa_country_code': 'TO',
  'fao_country_name': 'Togo'},
 {'country_name': 'Tokelau',
  'FIPS_10_country_code': 'TL',
  'noaa_country_code': 'TL',
  'fao_country_name': 'Tokelau'},
 {'country_name': 'Tonga',
  'FIPS_10_country_code': 'TN',
  'noaa_country_code': 'TN',
  'fao_country_name': 'Tonga'},
 {'country_name': 'Trinidad and Tobago',
  'FIPS_10_country_code': 'TD',
  'noaa_country_code': 'TD',
  'fao_country_name': 'Trinidad and Tobago'},
 {'country_name': 'Tunisia',
  'FIPS_10_country_code': 'TS',
  'noaa_country_code': 'TS',
  'fao_country_name': 'Tunisia'},
 {'country_name': 'Turkey',
  'FIPS_10_country_code': 'TU',
  'noaa_country_code': 'TU',
  'fao_country_name': 'Turkey'},
 {'country_name': 'Turkmenistan',
  'FIPS_10_country_code': 'TX',
  'noaa_country_code': 'TX',
  'fao_country_name': 'Turkmenistan'},
 {'country_name': 'Turks and Caicos Islands',
  'FIPS_10_country_code': 'TK',
  'noaa_country_code': 'TK',
  'fao_country_name': 'Turks and Caicos Islands'},
 {'country_name': 'Tuvalu',
  'FIPS_10_country_code': 'TV',
  'noaa_country_code': 'TV',
  'fao_country_name': 'Tuvalu'},
 {'country_name': 'Uganda',
  'FIPS_10_country_code': 'UG',
  'noaa_country_code': 'UG',
  'fao_country_name': 'Uganda'},
 {'country_name': 'Ukraine',
  'FIPS_10_country_code': 'UP',
  'noaa_country_code': 'UP',
  'fao_country_name': 'Ukraine'},
 {'country_name': 'United Arab Emirates',
  'FIPS_10_country_code': 'AE',
  'noaa_country_code': 'AE',
  'fao_country_name': 'United Arab Emirates'},
 {'country_name': 'United Kingdom of Great Britain and Northern Ireland',
  'FIPS_10_country_code': 'UK',
  'noaa_country_code': 'UK',
  'fao_country_name': 'United Kingdom of Great Britain and Northern Ireland'},
 {'country_name': 'United States of America',
  'FIPS_10_country_code': 'US',
  'noaa_country_code': 'US',
  'fao_country_name': 'United States of America'},
 {'country_name': 'Uruguay',
  'FIPS_10_country_code': 'UY',
  'noaa_country_code': 'UY',
  'fao_country_name': 'Uruguay'},
 {'country_name': 'Uzbekistan',
  'FIPS_10_country_code': 'UZ',
  'noaa_country_code': 'UZ',
  'fao_country_name': 'Uzbekistan'},
 {'country_name': 'Vanuatu',
  'FIPS_10_country_code': 'NH',
  'noaa_country_code': 'NH',
  'fao_country_name': 'Vanuatu'},
 {'country_name': 'Venezuela (Bolivarian Republic of)',
  'FIPS_10_country_code': 'VE',
  'noaa_country_code': 'VE',
  'fao_country_name': 'Venezuela (Bolivarian Republic of)'},
 {'country_name': 'Viet Nam',
  'FIPS_10_country_code': 'VN',
  'noaa_country_code': 'VM',
  'fao_country_name': 'Viet Nam'},
 {'country_name': 'Virgin Islands (British)',
  'FIPS_10_country_code': 'VI',
  'noaa_country_code': 'VI',
  'fao_country_name': 'Virgin Islands (British)'},
 {'country_name': 'Virgin Islands (U.S.)',
  'FIPS_10_country_code': 'VQ',
  'noaa_country_code': 'VQ',
  'fao_country_name': 'Virgin Islands (U.S.)'},
 {'country_name': 'Wallis and Futuna',
  'FIPS_10_country_code': 'WF',
  'noaa_country_code': 'WF',
  'fao_country_name': 'Wallis and Futuna'},
 {'country_name': 'Western Sahara',
  'FIPS_10_country_code': 'WI',
  'noaa_country_code': 'WI',
  'fao_country_name': 'Western Sahara'},
 {'country_name': 'Yemen',
  'FIPS_10_country_code': 'YM',
  'noaa_country_code': 'YM',
  'fao_country_name': 'Yemen'},
 {'country_name': 'Zambia',
  'FIPS_10_country_code': 'ZA',
  'noaa_country_code': 'ZA',
  'fao_country_name': 'Zambia'},
 {'country_name': 'Zimbabwe',
  'FIPS_10_country_code': 'ZI',
  'noaa_country_code': 'ZI',
  'fao_country_name': 'Zimbabwe'},
                        ]

uwm_location_to_fips_country_map = {
    "Central African Republic (South)": "CT",
    "Congo": "CF",
    "Congo Dem. Rep.": "CG",
    "Congo Dem. Rep. (North)": "CG",
    "Congo Dem. Rep. (Centre)": "CG",
    "Congo Dem. Rep. (South)": "CG",
    "Congo Dem. Rep. (Extr-South)": "CG",
    "North Korea": "KN",
    "North Korea (central bowl)": "KN",
    "Timor Leste": "TT",
    "French Guiana": "FG",
    "The Gambia": "GA",
    "Ghana (South)": "GH",
    "Ghana (North)": "GH",
    "Haiti": "HA",
    "Indonesia (Java)": "ID",
    "Indonesia (South Sulawesi (east))": "ID",
    "Indonesia (South Sulawesi (west))": "ID",
    "Indonesia (Sumatra)": "ID",
    "Cote d'Ivoire": "IV",
    "Malaysia (Sabah prov.)": "MY",
    "Malaysia (Sarawak prov.)": "MY",
    "Myanmar": "BM",
    "Nigeria (South)": "NI",
    "Nigeria (North)": "NI",
    "Somalia": "SO",
    "South Africa (West)": "SF",
    "South Korea": "KS",
    "Sudan (South)": "OD",
    "Sudan (North)": "SU",
    "Tanzania (South)": "TZ",
    "Tanzania (North)": "TZ",
    "Trinidad & Tobago": "TD",
    "Uganda (South)": "UG",
    "Uganda (North)": "UG",
    "Brazil (Center-South)": "BR",
    "Brazil (Rio Grande do Sul)": "BR",
    "Brazil (Northeast)": "BR",
    "Canadian Prairies (Alberta, Saskatchewan, Manitoba)": "CA",
    "Ontario & Quebec": "CA",
    "China (north)": "CH",
    "China (North China Plain)": "CH",
    "China (North China Plain and Manchuria)": "CH",
    "China (south)": "CH",
    "Mexico (not northwest)": "MX",
    "Mexico (NW)": "MX",
    "Brazil (North & Northeast)": "BR",
    "Czechoslovakia": "EZ",
    "Yugoslavia (Former)": "RI",
    "India (North)": "IN",
    "Burma (Myanmar)": "BM",
    "Thailand (central & northern)": "TH",
    "Thailand (NE)": "TH",
    "Vietnam (North)": "VN",
    "Vietnam (South)": "VN",
    "Indonesia (S. Sumatra & E. Java)": "ID",
    "South Africa (East)": "SF",
    "South Africa (except Western Cape)": "SF",
    "China (Sichuan, Hubei and Hunan)": "CH",
    "China (South)": "CH",
    "Mexico (Yucatan)": "MX",
    "Alaska": "US",
    "California": "US",
    "Colorado": "US",
    "Idaho": "US",
    "Kansas": "US",
    "Michigan": "US",
    "Minnesota": "US",
    "Montana": "US",
    "Nebraska": "US",
    "Nevada": "US",
    "North Dakota": "US",
    "Oregon": "US",
    "South Dakota": "US",
    "Utah": "US",
    "Washington": "US",
    "Wisconsin": "US",
    "Wyoming": "US",
    "Arizona": "US",
    "Delaware": "US",
    "Kentucky": "US",
    "Maryland": "US",
    "New Jersey": "US",
    "North Carolina": "US",
    "Oklahoma": "US",
    "Pennsylvania": "US",
    "South Carolina": "US",
    "Texas": "US",
    "Virginia": "US",
    "New Mexico": "US",
    "New York": "US",
    "Alabama": "US",
    "Arkansas": "US",
    "Florida": "US",
    "Illinois": "US",
    "Indiana": "US",
    "Iowa": "US",
    "Louisiana": "US",
    "Mississippi": "US",
    "Missouri": "US",
    "Ohio": "US",
    "Tennessee": "US",
    "West Virginia": "US",
    "Maine": "US",
    "Massachusetts": "US",
    "Rhode Island": "US",
    "Andhra Pradesh": "IN",
    "Assam": "IN",
    "Gujarat": "IN",
    "Himachal Pradesh": "IN",
    "Karnataka": "IN",
    "Kerala": "IN",
    "Maharashtra": "IN",
    "Orissa": "IN",
    "Rajasthan": "IN",
    "Tamil Nadu": "IN",
    "West Bengal": "IN",
    "New South Wales": "AS",
    "Queensland": "AS",
    "South Australia": "AS",
    "Victoria": "AS",
    "Western Australia": "AS",
    "Altai Krai": "RS",
    "Bashkir ASSR": "RS",
    "Central and Western Ukraine": "UP",
    "Chelyabinsk": "RS",
    "Eastern and Southern Ukraine": "UP",
    "Kirovohrad": "RS",
    "Kursk": "RS",
    "Northeastern Ukraine": "UP",
    "Novosibirsk and Omsk": "",
    "Orenburg": "RS",
    "Rostov": "RS",
    "Saratov": "RS",
    "Southern Ukraine": "UP",
    "Stavropol Krai": "RS",
    "Voronezh": "RS",
}

uwm_unnecessary_cols = ['notes', 'full_crop_name', 'data_id', 'unnamed:_0', 'level', 'qualifier', 'plant_start', 'plant_end', 'plant_end_date', 'plant_median', 'plant_range', 'harvest_start', 'harvest_start_date', 'harvest_end', 'harvest_median', 'harvest_range',     'source', 'x', 'tot_days', 'harvested_area', 'tmin_day_avg', 'temp_average', 'precip_average', 'temp_min', 'precip_min', 'temp_max', 'precip_max', 'temp_min_month', 'precip_min_month', 'temp_max_month', 'precip_max_month', 'temp_at_planting', 'precip_at_planting', 'sunfrac_at_planting', 'daylength_at_planting', 'dsw_at_planting', 'precip_over_pet_min', 'precip_over_pet_min_day',     'precip_over_pet_max', 'precip_over_pet_max_day', 'precip_over_pet_at_planting', 'apr_to_sept_temp_anomaly',   'apr_to_sept_precip_frac', 'gdd_base_0_between_plant_and_harvest', 'gdd_base_4_between_plant_and_harvest',   'gdd_base_5_between_plant_and_harvest', 'gdd_base_8_between_plant_and_harvest',     'gdd_base_10_between_plant_and_harvest', 'gdd_base_0', 'gdd_base_4', 'gdd_base_5', 'gdd_base_8', 'gdd_base_10', 'gdd_base_0_from_plant_until_cold', 'gdd_base_4_from_plant_until_cold',     'gdd_base_5_from_plant_until_cold', 'gdd_base_8_from_plant_until_cold', 'gdd_base_10_from_plant_until_cold', 'ndays_growing_season_below_0', 'ndays_growing_season_below_5', 'ndays_growing_season_below_10',   'ndays_growing_season_below_12', 'ndays_growing_season_below_15', 'ndays_growing_season_below_17', 'ndays_below_0', 'ndays_below_5', 'ndays_below_10', 'ndays_below_12', 'ndays_below_15', 'ndays_below_17',     'lgp', 'lgp_t', 'lgp_p', 'lgp_tmin5_tmax100', 'lgp_t_tmin5_tmax100', 'lgp_p_tmin5_tmax100', 'temp_growing_season', 'precip_growing_season', 'ndays_since_snowfrac_0_5', 'ndays_since_snowfrac_0_1',     'ndays_since_snowfrac_0_05', 'ndays_since_snowfrac_0', 'climate_category', 'misclassified', 'climate_category_string']
